### ISSUE TITLE
Failed to install 'cordova-plugin-actionsheet': Error: Uh oh!

### ISSUE THREAD

**Issue by lkrubner** [EddyVerbruggen/cordova-plugin-actionsheet#67]
If I do this: 

     cordova plugin add cordova-plugin-actionsheet

I get:

    cordova plugin add cordova-plugin-actionsheet
    Installing "cordova-plugin-actionsheet" for android
    Error during processing of action! Attempting to revert...
    Failed to install 'cordova-plugin-actionsheet': Error: Uh oh!
    ENOENT: no such file or directory, open '/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/plugins/cordova-plugin-actionsheet/www/ActionSheet.js'
        at Error (native)
        at Object.fs.openSync (fs.js:640:18)
        at Object.fs.readFileSync (fs.js:508:33)
        at install (/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/platforms/android/cordova/lib/pluginHandlers.js:173:36)
        at Object.process (/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
        at PluginManager.doOperation (/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
        at PluginManager.addPlugin (/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
        at /Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/platforms/android/cordova/Api.js:243:74
        at _fulfilled (/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/platforms/android/cordova/node_modules/q/q.js:854:54)
        at self.promiseDispatch.done (/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/platforms/android/cordova/node_modules/q/q.js:883:30)
    Error: Uh oh!
    ENOENT: no such file or directory, open '/Users/lkrubner/projects/chet/peero.mobile-dev.2018-03-21/plugins/cordova-plugin-actionsheet/www/ActionSheet.js'

My ionic info:

    ionic info
    
    cli packages: (/usr/local/lib/node_modules)
    
        @ionic/cli-utils  : 1.19.2
        ionic (Ionic CLI) : 3.20.0
    
    global packages:
    
        cordova (Cordova CLI) : 7.1.0 
    
    local packages:
    
        @ionic/app-scripts : 3.1.8
        Cordova Platforms  : android 6.3.0 browser 5.0.3 ios 4.5.4
        Ionic Framework    : ionic-angular 3.7.1
    
    System:
    
        ios-deploy : 1.9.2 
        Node       : v6.5.0
        npm        : 5.8.0 
        OS         : macOS High Sierra
        Xcode      : Xcode 9.2 Build version 9C40b 
    
    Environment Variables:
    
        ANDROID_HOME : /usr/local/Caskroom/android-sdk/3859397/
    
    Misc:
    
        backend : pro

**Comment by Nathan187** [comment]
did you every figure this out?  what the problem was?

**Comment by lkrubner** [comment]
I never figured it out. I did keep updating XCode, all plugins, the OS, etc, and eventually something worked. I think I tried some other commands.
